"""
YOLOv8 fine-tune wrapper for the rover's 8-class detector.

Wraps the ultralytics CLI with:
  - canonical class list from team/main/labeling/classes.txt (load-bearing order)
  - auto train/val split if the dataset is flat (images/ + labels/)
  - data.yaml generation
  - 320x320 imgsz default (matches PROJECT_PLAN §4-A)
  - pre-flight check that every label uses class IDs < 8

Dataset layouts accepted:
  (A) flat:
      <dataset>/images/*.jpg
      <dataset>/labels/*.txt
      -> 80/20 train/val split by stable hash of the filename
  (B) pre-split (Roboflow / CVAT style):
      <dataset>/train/images/*.jpg  + <dataset>/train/labels/*.txt
      <dataset>/val/images/*.jpg    + <dataset>/val/labels/*.txt
      (or "valid" instead of "val")

Usage:
  # Colab / GPU machine, after CVAT export
  python3 train_yolo.py --dataset /content/rover_yolo_v1 \
                        --epochs 100 --imgsz 320 --batch 32

  # Outputs:
  #   <dataset>/data.yaml
  #   runs/detect/train*/weights/best.pt   (ultralytics default)
"""
import argparse
import hashlib
import sys
from pathlib import Path


CANONICAL_CLASSES_PATH = (
    Path(__file__).resolve().parents[3] / "labeling" / "classes.txt"
)


def load_classes() -> list:
    if not CANONICAL_CLASSES_PATH.exists():
        raise SystemExit(f"missing canonical classes file: {CANONICAL_CLASSES_PATH}")
    classes = [
        line.strip()
        for line in CANONICAL_CLASSES_PATH.read_text().splitlines()
        if line.strip()
    ]
    if len(classes) != 8:
        raise SystemExit(f"expected 8 classes, got {len(classes)}: {classes}")
    return classes


def detect_layout(dataset: Path) -> str:
    flat = (dataset / "images").is_dir() and (dataset / "labels").is_dir()
    train = (dataset / "train" / "images").is_dir()
    val = (dataset / "val" / "images").is_dir() or (
        dataset / "valid" / "images"
    ).is_dir()
    if train and val:
        return "split"
    if flat:
        return "flat"
    raise SystemExit(
        f"unrecognized dataset layout under {dataset}. Need either "
        "images/+labels/ (flat) or train/{images,labels} + val/{images,labels}."
    )


def split_flat(dataset: Path, val_frac: float = 0.2) -> tuple:
    """Stable 80/20 split by hash. Returns (train_imgs, val_imgs)."""
    imgs = sorted((dataset / "images").glob("*.jpg"))
    train, val = [], []
    for p in imgs:
        h = int(hashlib.md5(p.name.encode()).hexdigest(), 16)
        if (h % 100) < int(val_frac * 100):
            val.append(p)
        else:
            train.append(p)
    return train, val


def write_split_lists(dataset: Path, train: list, val: list) -> tuple:
    train_txt = dataset / "train.txt"
    val_txt = dataset / "val.txt"
    train_txt.write_text("\n".join(str(p.resolve()) for p in train) + "\n")
    val_txt.write_text("\n".join(str(p.resolve()) for p in val) + "\n")
    return train_txt, val_txt


def preflight_labels(dataset: Path, n_classes: int) -> None:
    """Scan every .txt and verify class IDs are in [0, n_classes)."""
    bad = []
    for txt in dataset.rglob("*.txt"):
        if txt.name in ("classes.txt", "train.txt", "val.txt"):
            continue
        for ln, line in enumerate(txt.read_text().splitlines(), start=1):
            line = line.strip()
            if not line:
                continue
            try:
                cls = int(line.split()[0])
            except (ValueError, IndexError):
                bad.append(f"{txt}:{ln} unparsable: {line!r}")
                continue
            if not (0 <= cls < n_classes):
                bad.append(f"{txt}:{ln} class={cls} out of [0,{n_classes})")
    if bad:
        print("[preflight] label issues:")
        for b in bad[:20]:
            print(" ", b)
        if len(bad) > 20:
            print(f"  ... and {len(bad) - 20} more")
        raise SystemExit("fix label files before training")


def write_data_yaml(dataset: Path, classes: list, layout: str,
                    train_path: Path, val_path: Path) -> Path:
    data_yaml = dataset / "data.yaml"
    body = [
        f"# auto-generated by train_yolo.py — 8-class rover YOLO",
        f"path: {dataset.resolve()}",
        f"train: {train_path.relative_to(dataset)}",
        f"val: {val_path.relative_to(dataset)}",
        f"nc: {len(classes)}",
        f"names:",
    ]
    for i, name in enumerate(classes):
        body.append(f"  {i}: {name}")
    data_yaml.write_text("\n".join(body) + "\n")
    return data_yaml


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", type=Path, required=True,
                    help="dataset root (CVAT/Roboflow export or flat dir)")
    ap.add_argument("--model", default="yolov8n.pt",
                    help="pretrained weights (will be downloaded if missing)")
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--imgsz", type=int, default=320,
                    help="training image size; 320 matches PROJECT_PLAN §4-A")
    ap.add_argument("--batch", type=int, default=32)
    ap.add_argument("--device", default=None,
                    help="ultralytics device, e.g. '0' or 'cpu'")
    ap.add_argument("--val-frac", type=float, default=0.2,
                    help="val split fraction when --dataset is flat")
    ap.add_argument("--name", default="rover_yolo",
                    help="ultralytics run name")
    ap.add_argument("--no-preflight", action="store_true",
                    help="skip class-id range check")
    ap.add_argument("--dry-run", action="store_true",
                    help="prepare data.yaml and exit without training")
    args = ap.parse_args()

    if not args.dataset.is_dir():
        raise SystemExit(f"dataset not found: {args.dataset}")
    classes = load_classes()
    print(f"[classes] {len(classes)}: {classes}")

    if not args.no_preflight:
        preflight_labels(args.dataset, len(classes))

    layout = detect_layout(args.dataset)
    print(f"[layout] {layout}")

    if layout == "flat":
        train, val = split_flat(args.dataset, args.val_frac)
        print(f"[split] train={len(train)} val={len(val)}"
              f" (hash-stable, val_frac={args.val_frac})")
        train_path, val_path = write_split_lists(args.dataset, train, val)
    else:
        train_path = (args.dataset / "train" / "images").resolve()
        val_dir = args.dataset / "val"
        if not val_dir.is_dir():
            val_dir = args.dataset / "valid"
        val_path = (val_dir / "images").resolve()

    data_yaml = write_data_yaml(args.dataset, classes, layout,
                                train_path, val_path)
    print(f"[data.yaml] {data_yaml}")
    print(data_yaml.read_text())

    if args.dry_run:
        print("[dry-run] not training. data.yaml ready.")
        return

    try:
        from ultralytics import YOLO
    except ImportError:
        raise SystemExit(
            "ultralytics not installed. Run: pip install ultralytics"
        )

    model = YOLO(args.model)
    print(f"[train] model={args.model} epochs={args.epochs} "
          f"imgsz={args.imgsz} batch={args.batch}")
    model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        name=args.name,
    )
    print("[done] best weights typically at runs/detect/<name>*/weights/best.pt")
    print("[next] export ONNX then build TRT engine with"
          " scripts/export_yolo_to_trt.sh (TODO)")


if __name__ == "__main__":
    main()
